### PR TITLE
added grid support to foulplay

### PR DESCRIPTION
**Pull request by junklight**
grid support

### CODE REVIEW

**Comment by junklight** [comment]
I tested your new logic stuff (nice feature BTW) and it all works - note that muting a target track doesn't stop it effecting the logic. I _think_ that's the right behaviour

**Comment by notjustmat** [comment]
Wow! Thanks for getting to this so quickly! I will check this out/ test it this evening. Assuming everything works fine on hardware, I'll update the dust/docs with a image of the grid controls and PR tomorrow. 

Also, re: mute/logic. That sounds right to me :)

**Comment by junklight** [comment]
no worries 

the other thing I thought about adding was simple velocity patterns - like "Accent every other beat" "Accent every Nth beat" -  I like hats with louder/quieter/louder/etc.  and perhaps a bit of velocity humanisation. I couldn't see immediately how to add that - the Ack engine is quite complex but I'm sure it's there.

**Comment by notjustmat** [comment]
Just glanced over, and I noticed that your doc string wont work on norns, the screen is too small so it has to be rather terse. That stuff would go great in the markdown docs at dust/docs. 

[dust/docs](https://github.com/notjustmat/dust/blob/master/docs/justmat/foulplay/foulplay.md)

**Comment by junklight** [comment]
I've just been using maiden to read comments at top - hadn't really thought they go anywhere :-) 

I'll add them to docs instead - just found a bug so will need to do an update

**Comment by junklight** [comment]
ha it's a bug in your code - line 321 view is spelt wrong - since it's only one word can I let you update that - I'm not sure my git fu (such that it is) is up to updating a PR without digging about!

**Comment by notjustmat** [comment]
Womp womp! Yeah, I'll fix that here.

**Comment by notjustmat** [comment]
I've just been using the grid functions, and it's pretty great! My only nit pick is wanting the dimly lit buttons to be just a bit brighter, with a sunny room they wash out completely. I would think maybe a 3 would be good. Other than that and the intro doc string, it looks good! 
Are you comfortable making those changes? If not, it's no problem for me to do it post merge.

**Comment by junklight** [comment]
ok - in theory have tweaked those

**Pull request merged**
